name: kanbored
description: "Kanbored"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  http:
  flutter_secure_storage:
  flutter_markdown:
  markdown:
  drift: ^2.17.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.9.0
  sqlite3:
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.17.0
  build_runner: ^2.4.9
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/amolded_theme.json
    - assets/dark_theme.json
    - assets/light_theme.json
    - assets/strings.json
